AWSTemplateFormatVersion: 2010-09-09
Description: >-
  JobApplications

Transform:
- AWS::Serverless-2016-10-31

Globals: 
  Api:
    Name: job-applications
    EndpointConfiguration: EDGE
  Function: 
    Environment:
      Variables:
        TABLE_NAME

Resources:
  JobApplicationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: JobApplicationsTable
      AttributeDefinitions:
        - AttributeName: job
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: job
          KeyType: HASH
        - AttributeName: Name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  JobApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: applicationProcessing.handler
      CodeUri: src/lambdas/applicationProcessing
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that processes job applications against a set of minimum requirements.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApplicationPost:
          Type: Api
          Properties:
            Path: /{job}/submit
            Method: POST
        ApplicationGet:
          Type: Api
          Properties:
            Path: /{job}/{Name}
            Method: GET
        ApplicationDelete:
          Type: Api
          Properties:
            Path: /{job}/{Name}
            Method: DELETE
        EmployerView:
          Type: Api
          Properties:
            Path: /{job}/list
            Method: GET
  
            
          
