AWSTemplateFormatVersion: 2010-09-09
Description: >-
  JobApplications

Transform:
- AWS::Serverless-2016-10-31

Globals: 
  Api:
    Name: job-applications

Resources:
  JobApplicationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: JobApplicationsTable
      AttributeDefinitions:
        - AttributeName: job
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: job
          KeyType: HASH
        - AttributeName: Name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  JobApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: applicationProcessing.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that processes job applications against a set of minimum requirements.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: JobApplicationsTable
      Events:
        ApplicationPost:
          Type: Api
          Properties:
            Path: /{job}/submit
            Method: POST
        EmployerView:
          Type: Api
          Properties:
            Path: /{job}/list
            Method: GET
        CriteriaPost:
          Type: Api
          Properties:
            Path: /{job}/criteria
            Method: POST
  
            
          
