AWSTemplateFormatVersion: 2010-09-09
Description: >-
  JobApplications

Transform:
- AWS::Serverless-2016-10-31

Resources:
  JobApplicationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: JobApplicationsTable
      AttributeDefinitions:
        - AttributeName: job
          AttributeType: S
      KeySchema:
        - AttributeName: job
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  JobApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/applicationSumbissionHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that processes job applications against a set of minimum requirements.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApplicationPost:
          Type: Api
          Properties:
            Path: /{job}/submit
            Method: POST
  
            
          
